site_name: VCCSD Docs Pro
site_description: Production docs starter with search, i18n, versions, blog and API reference.
site_url: https://USERNAME.github.io/REPO/
repo_url: https://github.com/USERNAME/REPO
repo_name: REPO
edit_uri: edit/main/docs/
use_directory_urls: true
copyright: Copyright &copy; 2026

theme:
  name: material
  language: cs
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - announce.dismiss
  palette:
    - scheme: slate
      primary: slate
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Dark mode

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/site-meta.js
  - assets/js/app.js
  - assets/js/openapi.js
  - assets/js/mermaid-lite.js

extra:
  generator: false
